### ISSUE TITLE
time  

### ISSUE THREAD

**Issue by sunzhe09** [cure-lab/DirectInversion#1]

**Comment by sunzhe09** [comment]
I have test the run_editing_p2p_one_image.py I find directinversion+p2p cost 62 seconds,but ddim+p2p cost 44 seconds ,it's right?

**Comment by juxuan27** [comment]
Hi, @sunzhe09 . Our method can achieve a better result than sota optimization-based methods with a faster running speed. How, Direct Inversion would be a little slower than DDIM Inversion since it needs an additional forward as explained in the main paper. Noted that running time would be different on different machine.

**Comment by sunzhe09** [comment]
OK，my device is V100
