### ISSUE TITLE
Can null-text inversion run in different diffusers versions?

### ISSUE THREAD

**Issue by chenxinglili** [cure-lab/DirectInversion#3]
Hi, I have trained a base diffusion model under diffusers==0.19.3.
I would like to ask if it is possible to use null-text inversion+p2p to edit images based on this model and diffusers==0.19.3.

**Comment by juxuan27** [comment]
Hi, @chenxinglili ! Thank you for your focus. Bur unfortunately, since prompt2prompt has a strict requirement for diffusers version. You have to use the given version in our requirements.txt. If you do want to use your own model, you may need to do some changes for the attention manipulation in our code (e.g. change variable name to adapt to your diffusers version).

**Comment by chenxinglili** [comment]
I would like to ask which edit method in your code can support higher versions of diffusers?

**Comment by juxuan27** [comment]
You may refer to https://github.com/cure-lab/DirectInversion/tree/main/environment to see which diffuser version is compatible with your requirements.
